name: Docker image validation

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-verification.yml'
    types: [opened, synchronize, reopened]

# Declare default permissions as read only.
permissions:
  contents: read
  actions: read

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Validate Docker container
        run: |
          set -e
          
          docker build -t rmoreliovlabs/rskj:latest .
          container_id=$(docker run -d --name rskj-container rmoreliovlabs/rskj:latest --regtest)
          trap 'docker stop "$container_id"' EXIT INT QUIT TERM
          
          # Give a couple of seconds for the container to start.
          sleep 5
          
          if [ "$(docker inspect -f '{{.State.Running}}' rskj-container)" != "true" ]; then
          echo "Container failed to start"
          exit 1
          fi
          
          max_attempts=20
          attempts=0
          count=0
          
          while [ $attempts -lt $max_attempts ]; do
          count=$(docker logs rskj-container | grep -c "IMPORTED_BEST")
          
          if [ $count -gt 0 ]; then
          echo "✅ Found 'IMPORTED_BEST' block in logs!"
          break
          fi
          
          echo "Waiting for 5 seconds for blocks to be imported..."
          sleep 5
          echo "Continuing to check imported blocks"
          
          attempts=$(($attempts + 1))
          done
          
          if [ $count -le 0 ]; then
          echo "❌ 'IMPORTED_BEST' block not found in logs after $max_attempts attempts"
          exit 1
          fi
          
          echo "Container is running properly"
