name: Docker image validation

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-verification.yml'
    types: [opened, synchronize, reopened]

# Declare default permissions as read only.
permissions: read-all

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Build Docker image for validation
        run: |
          docker build -t rsksmart/rskj:latest .

      - name: Run Docker container
        run: |
          docker run -d --name rskj-container rsksmart/rskj:latest --regtest

      - name: Check Docker container built
        run: |
          ./validate-docker-container.sh
